### ISSUE TITLE
External manuals: "Edit this document" link is not working

### ISSUE THREAD

**Issue by silviot** [collective/collective.developermanual#176]
When I go to
http://developer.plone.org/reference_manuals/external/plone.app.robotframework/happy.html

and I click "Edit this document" I get a github 404: https://github.com/collective/collective.developermanual/blob/master/source/reference_manuals/external/plone.app.robotframework/happy.rst .

I guess this has to do with the "/external/" part of the url, but I still don't know the structure of the documentation.

Anyway, either there should be no "Edit this document" button or if it's there it should work.

**Comment by miohtama** [comment]
/external/ part documents are in different Git repository.

Currently the link makes dummy assumption about where on Github URL you can find the document, because this information is not availble in Sphinx.

However, I some time ago started to work on code which would map any filesystem path to its Github URL as long as the file is in git repo. It is not there, yet.

What we could do meanwhile is that in "Edit" JavaScript snippet detect /external/ in URL and tell the user to go to github.com/plone or github.com/collective and find the source there.

**Comment by svx** [comment]
I will close this the new setup is different and this will not be fixed in the current situation/setup
