### ISSUE TITLE
Have working Travis CI notifications

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#95]

**Comment by witekdev** [comment]
Witek is working on this to fix Sphinx recipe to return proper exit code (failure, success) to travis, so travis can report failures.

so, if I understand correctly.
as per - http://about.travis-ci.org/docs/user/build-configuration/
under "Build Lifecycle" heading
The standard Unix exit code of "0" means the build passed; everything else is treated as failure.
so im no python expert but googling for "python exit code of 0"
This means that sphinx needs to terminate with sys.exit(1) or anything other than sys.exit(0), in order to indicate a failure of the build.

ok, 
The original starting point for this task was to modify collective.recipe.sphinxbuilder recipe.
However after inspection, it seems that this is not something that can be fixed by changing the collective.recipe.sphinxbuilder recipe.

This recipe is broken down into logical parts:
        # 1. CREATE BUILD FOLDER IF IT DOESNT EXISTS  
        # 2. RESOLVE SOURCE PATH  
        # 3. CREATE MAKEFILE (MAKEFILE code comes from sphinx.quickstart)
        # 4. CREATE BATCHFILE (BATCHFILE code comes from sphinx.quickstart)
        # 4. CREATE CUSTOM "sphinx-build" SCRIPT
        # 5. INSTALL SPHINX WITH SCRIPT AND EXTRA PATHS

None of which really allow you to change how sphinx terminates itself.

Another place where one can configure sphinx behaviour is its conf.py file.
http://sphinx-doc.org/config.html
and while, there is an option to "keep_warnings"
"If true, keep warnings as “system message” paragraphs in the built documents. Regardless of this setting, warnings are always written to the standard error stream when sphinx-build is run.
The default is False, the pre-0.5 behavior was to always keep them. New in version 0.5."
This is not what we want.

What I have arrived at ultimately is that in the sphinx itself, there are a lot of statements:
"return 1" 
(mostly in sphinx/cmdline.py which is called by sphinx/**init**.py)

Where I am now with this ticket is that I suspect that these "return 1" need to be changed to sys.exit(1) or something like that? In order for python to correctly exit with a unit exit code of "0", that Travis can pick up on?

This would mean that we would have to modify sphinx project source?

I want to figure out how I can test this theory of mine in a sandboxed way so that I'm not making a mess.

any comments anyone?

**Comment by miohtama** [comment]
Nice, a lot of info!

I think Sphinx itself performs correctly as you pointed out. I took the advice I changed the .travis.yml file as the following
- Sphinx is performed by a command bin/sphinx-build which is created by https://github.com/garbas/collective.recipe.sphinxbuilder. It has this part which "forgets" the return value
  
  import sphinx
  
  if **name** == '**main**':
      sphinx.main() # Adding sys.exit(sphinx.main()) here?
- This command is called by "make html"
- Makefile properly delegages all error return values to to anyone who called "make"
- ... so what we could do is
- Have another section in Makefile called "warnings-html" and then .travis.yml runs this command
- This does the same thing than "make html" but treats warnings as errors. We can just copy paste make html section and add the sphinx switch "treat warnings as errors"
- So on the warning, bin/sphinx-build should spit out the sys.exit() code 1
- make pushes this exit code to travis, which does the build failure thing

**Comment by witekdev** [comment]
ok,
so that means that we have to
- modify the https://github.com/garbas/collective.recipe.sphinxbuilder, to make sure that it creates
  
  import sphinx
  
  if name == '**main**':
  sys.exit(sphinx.main())
- embed the MAKEFILE and BATCHFILE sources in the collective.recipe.sphinxbuilder/**init**.py itself, as at the moment they are being imported from sphinx itself by the recipe:
  
  from sphinx.quickstart import MAKEFILE
  from sphinx.quickstart import BATCHFILE
  
  because we dont want to modify sphinx itself, we want to make local changes in our recipe only. 
  We then modify them as you described above.

quite honestly I'm also confused as to why there is the make.bat and Makefile. I'm happy to modify them both, but they seem to be almost identical with slightly different syntax?

also as far as the first bullet point is concerned:

import sphinx
if name == '**main**':
sphinx.main()

is created by buildout:

```
    zc.buildout.easy_install.scripts(
            [('sphinx-quickstart', 'sphinx.quickstart', 'main'),
             ('sphinx-build', 'sphinx', 'main')], ws,
            self.buildout[self.buildout['buildout']['python']]['executable'],
            self.bin_dir, **egg_options)
```

so unless there is an option/switch somewhere in zc.buildout to wrap your "main()" in sys.exit() (which I doubt)
then we need to, right after that buildout line has run, manually do some modifications on the newly created bin/sphinx-build script.

that seems a bit hacky, but ok, open file and replace sphinx.main() with sys.exit(sphinx.main()), close file. right before the install method of the recipe returns. right?

**Comment by witekdev** [comment]
ok, so I forked from
https://github.com/sdouche/collective.recipe.sphinxbuilder
to
https://github.com/witekdev/collective.recipe.sphinxbuilder
sdouche branch was more recent than garbas branch.

made changes as described in previous comment and labeled release 0.7.3
now a pull-request and then hopefully from there on a release to pypi?
(I dont know how to do that.)

to build with the "warnings into errors" option
you now have to call
"build/make warnings-html"
if you call 
"make warnings-html" from the root of your buildout, it wont find the option of warnings-html (I dont know why)
but "build/make warnings-html" works

here is a link to sphinx-build options:
http://sphinx-doc.org/invocation.html

**Comment by miohtama** [comment]
We can also use trunk version of collective.recipe.sphinxbuilder with mr. developer in buildout.cfg, so we don't need to wait for the release. 

I'll poke Rok in any case to get release done.

I'll check the make warnings-html thing.

**Comment by witekdev** [comment]
Right, we dont have to wait for a release.
but just so you know  I've already made a pull-request to sdouche to merge and make a release.

**Comment by svx** [comment]
we will not fix that for this setup, we are on the move !
